-- phpMyAdmin SQL Dump
-- version 5.1.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Tempo de geração: 15-Dez-2021 às 04:15
-- Versão do servidor: 10.4.22-MariaDB
-- versão do PHP: 8.0.13

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Banco de dados: `culturela`
--

-- --------------------------------------------------------

--
-- Estrutura da tabela `contato`
--

CREATE TABLE `contato` (
  `id` int(11) NOT NULL,
  `nome` varchar(45) NOT NULL,
  `sobrenome` varchar(45) DEFAULT NULL,
  `email` varchar(45) DEFAULT NULL,
  `assunto` text DEFAULT NULL,
  `created` datetime NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Extraindo dados da tabela `contato`
--

INSERT INTO `contato` (`id`, `nome`, `sobrenome`, `email`, `assunto`, `created`) VALUES
(0, 'VITOR SANTOS', 'SILVA', 'vitorssilva230@gmail.com', 'uuuuuuuu', '2021-12-14 21:14:46');

-- --------------------------------------------------------

--
-- Estrutura da tabela `culture_data`
--

CREATE TABLE `culture_data` (
  `id` int(10) UNSIGNED NOT NULL,
  `nome` varchar(255) NOT NULL,
  `descricao` text NOT NULL,
  `epoca_de_plantio` varchar(255) NOT NULL,
  `plantio` text NOT NULL,
  `rega` text NOT NULL,
  `adubacao` text NOT NULL,
  `floramento_colheita` text NOT NULL,
  `url_img` text NOT NULL,
  `id_categoria` int(11) NOT NULL,
  `id_subcategoria` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Extraindo dados da tabela `culture_data`
--

INSERT INTO `culture_data` (`id`, `nome`, `descricao`, `epoca_de_plantio`, `plantio`, `rega`, `adubacao`, `floramento_colheita`, `url_img`, `id_categoria`, `id_subcategoria`) VALUES
(0, 'Lírio da paz', 'É uma planta tropical, herbácea, perene, com altura de 60 a 70 cm, sua inflorescência é branca e possui cheiro (esta espécie). Pode ser cultivada em vasos ou jardineiras e deve ser mantida a meia sombra.\r\n\r\n', 'Março a abril para as regiões Sudeste, Centro-Oeste e Nordeste e junho a julho para a região Sul. ', 'Podem ser facilmente propagados por divisão de touceiras durante qualquer estação do ano. Também pode utilizar sementes.', 'Regar até o solo se manter bem úmido, mas não encharcado. Regue sempre que as flores aparentarem estarem murchando. Geralmente, a rega é feita 3 a 4 vezes por semana.', 'Não precisa adubar, apenas as cultive em solos ricos em nutrientes, como terra preta. ', '2 vezes ao ano. Entre janeiro e março e julho e setembro.', 'imagens_banco_de_dados/lirio_da_paz.jpeg', 1, 1),
(1, 'Comigo-ninguém-pode', 'Planta perene, com folhas grandes, vistosas, verdes com manchas esbranquiçadas e caule espesso. É uma planta tóxica, porém só causa danos se for ingerida. Portanto tenha cuidado e evite colocá-la em ambientes com crianças e animais domésticos. São plantas que podem ser cultivadas em vasos a sombra ou meia sombra e devem ficar em locais com pouco vento. A comigo-ninguém-pode é muito sensível a baixas temperaturas, sendo indicada somente para regiões tropicais e subtropicais.', 'Qualquer época do ano.', 'Pode ser multiplicada facilmente por estacas formadas a qualquer época do ano pelo corte do caule em pedaços menores, plantando-os em vasos ou no mesmo local', 'Se atente a regar quando o solo aparentar estar seco (o tempo pode ser diferente para cada época do ano e locais). Não encharque muito o solo.', 'NPK em pequenas doses. ', 'Não há.\r\n\r\n', 'imagens_banco_de_dados/comigo_ninguem_pode-2.jpg', 1, 1),
(3, 'Espada de São Jorge', 'Esta planta é bastante conhecida por crenças populares como planta de proteção contra o mau-olhado, geralmente disposta na entrada das casas. É uma planta herbácia com coloração verde acinzentada e variegadas, com margens de coloração branco-amareladas, todas com estriações de uma tonalidade mais escura. As flores brancas não têm importância ornamental. Cuidado! Ela é uma planta tóxica para animais domésticos, caso ingerida, portanto, deixe em locais onde eles não tenham acesso.', 'Podem ser facilmente propagados por divisão de seus caules durante qualquer estação do ano.', 'Podem ser facilmente propagados por divisão de seus caules durante qualquer estação do ano.', 'A espada-de-são-jorge pode ficar até 20 dias sem água, desde que esteja saudável. A irrigação deve ser espaçada, uma vez na semana é suficiente \r\n\r\n', 'Não precisa adubar, apenas as cultive em solos ricos em nutrientes, como terra preta. ', 'As espadas de são Jorge florescem e apresentam um perfume doce que se intensifica à noite. Não há um período certo para que haja o afloramento.\r\n\r\n', 'imagens_banco_de_dados/espada.jpg', 1, 1),
(4, 'Rosa do deserto', 'A rosa-do-deserto é uma planta domesticada da família Apocynaceae, e originalmente, pode ser encontrada em áreas desérticas da Tailândia e África, se adapta facilmente ao clima seco e quente e consegue viver bem em lugares ensolarados.', 'março a abril para as regiões Sudeste, Centro-Oeste e Nordeste e junho a julho para a região Sul. ', 'A rosa-do-deserto pode ser cultivada por sementes ou estacas. Os troncos grossos com a característica parecida com os grandes Baobás, só podem ser obtidos através do cultivo de semente. Para o plantio em vaso deve-se tomar cuidado com a drenagem, pois a rosa do deserto não resiste a solos encharcados, então, no fundo do vaso, coloque pedras e uma tela plástica para que as raízes não saiam por baixo do vaso\r\n\r\n', 'Quanto à irrigação, mantenha a areia ou a terra sempre úmida, porém sem encharcar. Não é necessário regar todos os dias, somente quando a areia ou a terra em cima do vaso secar.', 'Geralmente não é necessário a aplicação de adubos, mas o substrato deve ser composto uma parte de húmus de minhoca e uma mistura de 2/3 de areia grossa e 1/3 de solo argiloso \"terra\". ', 'Nos casos de enxertia, a floração da rosa do deserto ocorre, em média, de dois a três meses após o enxerto.', 'imagens_banco_de_dados/rosa_do_deserto.jpg', 1, 1),
(5, 'Colar de Pérolas', 'Esse tipo de suculenta é conhecido como colar-de-pérolas graças ao seu aspecto visual. As folhas parecem ervilhas ou um colar de pérolas verde quando a suculenta está pendente. Na primavera, ainda podem aparecer flores brancas e com cheiro de canela. Possui de 50 centímetros a 1 metro e, geralmente, é cultivada em vasos altos, para que as folhas fiquem pendentes, mas também pode ser cultivada de forma rasteira.', 'Todo o ano. \r\n\r\n', 'A propagação deste senécio pode ser feita com a técnica da estaquia. Deve-se cortar um pedaço de 10 cm da haste com as folhinhas e preparar um recipiente com areia, casca de arroz carbonizada, perlita ou vermiculita, regando abundantemente e deixando escorrer toda a água, então, deitar a haste sobre o substrato, procurando aderir bem os entrenós abaixo das folhas com a terra.', 'Quanto à rega, esta deve ser feita regularmente e de forma abundante, mas atenção, o substrato deve estar seco entre uma rega e outra.', 'A adubação pode ser feita duas vezes ao ano com húmus de minhoca, pó de café ou farinha de casca de ovo.', 'Não há.', 'imagens_banco_de_dados/colar_de_perolas.jpg', 1, 2),
(6, 'Rabo de burro', 'A rabo-de-burro é uma suculenta pendente muito charmosa. Suas folhas são carnudas e as suas flores pontiagudas, podendo ter cores variadas. As flores podem ser rosas, amarelas e até mesmo verdes. Varia de 60 centímetros a 1,2 metros', 'Todo o ano. ', 'São de fácil reprodução, é necessário apenas preparar um vaso com substrato e colocar uma folha de uma planta adulta sobre ele, não sendo necessário ficar coberta pelo solo.', 'São de fácil reprodução, é necessário apenas preparar um vaso com substrato e colocar uma folha de uma planta adulta sobre ele, não sendo necessário ficar coberta pelo solo.', 'A adubação pode ser feita com húmus de minhoca ou com NPK 10- 10- 10.', 'Não há.', 'imagens_banco_de_dados/Rabo_de_burro.jpg', 1, 2),
(7, 'Rosa de Pedra', 'Conhecida também como bola-de-neve mexicana, a rosa-de-pedra é uma das suculentas mais populares no Brasil. Sua aparência é de um desabrochar de uma rosa e as suas cores variam, podendo ser verde ou mais acinzentada. Possui cerca de 5 a 20 centímetros. Como ela é pequena, a rosa-de-pedra pode decorar ambientes internos, desde que fique perto de janelas iluminadas. No exterior da casa, você deve se lembrar de não deixar ela tomando sol o dia todo.', 'Todo ano.', 'A reprodução pode ser feita por separação de filhotes que surgem junto à planta-mãe, por divisão de touceiras e pela folha.', 'A rega deve ser feita uma vez por semana no verão e uma vez ou duas ao mês no inverno. ', 'A adubação pode ser feita de 4 em 4 meses, com adubos específicos para suculentas, preferencialmente.', 'Não há. ', 'imagens_banco_de_dados/rosa_de_pedra.jpg', 1, 2),
(8, 'Mandacaru', 'O mandacaru é uma planta nativa do Brasil, muito bem adaptada ao clima da região do semiárido brasileiro. Também conhecida como cardeiro, essa planta com formato que lembra um candelabro, pode alcançar até seis metros de altura e tem a grande vantagem de ser muito resistente às secas, graças a sua capacidade de captação e retenção de água.', 'Todo ano. ', 'Esse cacto é capaz de crescer raízes a partir de qualquer pedaço de seu caule que esteja em contato com o chão, portanto, para fazer uma nova muda basta cortar um pedaço de cerca de trinta centímetros do caule de um cacto adulto e replantá-lo (essa técnica recebe o nome de \"estaca\"). Depois de cerca de dois meses as novas raízes dessa muda já terão crescidos e ela será uma planta independente.', 'O mandacaru é uma planta resistente a seca, tome cuidado para não enxarcar o solo durante a rega, pois o excesso de água pode provocar o apodrecimento da planta.', 'Não necessita.', 'De novembro a janeiro apresenta flores brancas, com uma peculiaridade: elas florescem à noite e, logo pela manhã, murcham.', 'imagens_banco_de_dados/mandacaru.jpg', 1, 3),
(9, 'Rabo de macaco', 'Conhecido como Hildewintera colademononis, o cacto Rabo de Macaco é uma planta que leva esse nome por ter ramificações alongadas e peludas encobertas por uma infinidade de espinhos. Dessa forma, trazem a similaridade com o rabo do animal. Originária da Bolívia, essa planta é uma dentre as outras de sua família que não demandam muito cuidados e por isso, são perfeitos para as pessoas que não possuem muito tempo livre no dia a dia.', 'Todo ano. ', 'A propagação do cacto Rabo de Macaco pode ser realizada de duas maneiras muito simples: a primeira conduz o crescimento da planta mais rapidamente, feita pela transposição dos caules cortados do próprio cacto e plantados novamente na terra. Esse procedimento já foi ensinado logo acima.', 'Como o cacto Rabo de Macaco é uma planta que floresce nas estações da Primavera e do Verão, a sua irrigação deve ser feita exclusivamente durante essas épocas. Porém, como esses vegetais vivem em ambientes quentes e de temperatura elevada, eles deverão pedir mais regas.', 'Use uma misture de partes iguais de areia de construção e terra vegetal.\r\n\r\n', 'Nas estações da primavera e verão surgem pequenas e delicadas flores em um tom avermelhado em alguns pontos dos caules suspensos que contrastam com o tom verde característico do cacto, e desta podem surgir até pequenos frutos (não comestíveis).', 'imagens_banco_de_dados/rabo_de_macaco.jpg', 1, 3),
(10, 'Cacto parafuso', 'O cacto parafuso, popularmente conhecido como cacto colunar ou cacto espiral, tem como nome científico Cereus peruvianus e pertence à família Angiospermae. É um enorme arbusto nativo da América do Sul, em especial nas regiões secas do Peru. Pode chegar a medir 4 metros de altura e 12 centímetros de diâmetro.', 'Todo ano. ', 'O cacto parafuso pode ser propagado desde a sementes como também pode ser propagado por estacas, um método mais simples, pois é feito um corte na planta e, após deixar secar por uma semana, é colocado no solo.\r\nDepois de cerca de dois meses as novas raízes dessa muda já terão crescidos e ela será uma planta independente.\r\n', 'O cacto parafuso é uma planta que necessita de pouca água, o recomendado é que, para manter sua planta sempre bonita e saudável, o substrato seja regado uma vez por mês e somente quando o mesmo estiver completamente seco.', 'Não necessita.', 'A floração do cacto parafuso é uma cena espetacular, visto que é um fenômeno que acontece ao longo dos meses da primavera e verão, seu desabrochar ocorre durante a noite e exibe flores solitárias de pétalas e sépalas em tons brancos e lilases, e estão dispostas em pedúnculos espessos e espalhadas por quase toda suas hastes.', 'imagens_banco_de_dados/Cacto_Parafuso.jpg', 1, 3),
(11, 'Cacto orelha de Mickey', 'Opuntia microdasys, também conhecida como cacto orelha de coelho e cacto Mickey Mouse, é um cacto da família Cactaceae. Seus nomes populares derivam de sua aparência, pois a planta possui uma grande folha central e duas outras folhas menores grudadas nos dois cantos superiores, parecendo duas orelhinhas.', 'Todo ano. ', 'Para propagar uma Opuntia microdasys por estaca você vai precisar de uma parte da planta, pode ser uma das orelhinhas, quanto maior a estaca, maior as chances de sucesso. Depois, deixe a estaca cicatrizar por no mínimo 24 horas, em seguida, a plante em solo propício totalmente seco, espere por 1 semana antes de umedecê-la. Por fim, passado a primeira semana, borrife um pouco de água no solo para hidratar a muda, mas sem encharcar, e repita o processo toda vez que a terra secar completamente.\r\n\r\n', 'A Opuntia microdasys é um a planta que não necessita de regas frequentes, nem de muita umidade. Quando a for regar, certifique-se de que a terra esteja completamente seca, se você não tiver certeza, deixe secar por mais um dia e depois regue deixando a água escorrer pelos orifícios do vaso, o excesso de água pode carretar em uma Opuntia opaca e sem vida.', 'Não necessita.', 'A floração do cacto orelha de Mickey ocorre todo verão. \r\n\r\n', 'imagens_banco_de_dados/cacto_orelha de_mickey.jpg', 1, 3),
(12, 'Onze horas', 'A Portulaca grandiflora, conhecida popularmente como onze-horas, é uma planta nativa de regiões com temperaturas mais baixas, como o sudeste brasileiro. É uma espécie bem delicada e que possui uma floração muito abundante. Além disso, são classificadas como suculentas, ou seja, consomem pouca água e adoram sol.', 'Todo ano. ', 'Para cultivar a onze-horas em recipientes você deverá usar um vaso com furos no fundo, para que a água seja drenada adequadamente. Coloque argila expandida e após um pedaço de manta de bedim, caso não tenha pode usar qualquer tecido bom para filtragem.Para cultivar a onze-horas em recipientes você deverá usar um vaso com furos no fundo, para que a água seja drenada adequadamente. Coloque argila expandida e após um pedaço de manta de bedim, caso não tenha pode usar qualquer tecido bom para filtragem.\r\n\r\nDepois coloque terra, também pode usar esterco ou húmus, adicione um pouco de areia e misture bem. Pegue um galho de uma onze-horas adulta, retire as folhas e enterre este galho de 2 a 3 centímetros de profundidade, após é só umedecer o solo do recipiente.\r\n', 'A flor onze-horas não precisa de muita umidade, mesmo não sendo muito tolerante à seca, mas para florescer é importante um pouco de umidade de uma forma equilibrada. A rega pode ser realizada se houver um longo período sem chuva, no clima quente do verão uma rega deve ser o suficiente para o desenvolvimento saudável da flor.', 'Não necessita.', 'O segredo para que a onze-horas floresça bem está na umidade, se caso ela não esteja produzindo flores abundantes o suficiente, certamente algo errado com a umidade. Estas flores não gostam do solo úmido ou encharcado, e se estão em terrenos que retém muita umidade elas também não irão florescer.', 'imagens_banco_de_dados/onze_horas.jpg', 1, 4),
(13, 'Flor cosmos', 'A flor Cosmos é muito conhecida por sua beleza e por enfeitar qualquer jardim. Coloridas e extremamente belas, as flores Cosmos são plantas de floração anual, que costumam crescer facilmente em vários tipos de temperaturas e localidades. Por serem tão cheias de cores, a flor Cosmos também costuma atrair muitos insetos polinizadores durante a estação do verão.', 'Todo ano. ', 'A flor Cosmos se auto semeia, o que significa que ela é capaz de se propagar naturalmente, sem interferência humana. Embora semear seja o jeito melhor e mais fácil de propagar a Cosmos, ela também pode ser propagada através do corte do caule.\r\n\r\nQuando você corta o caule, estimula o crescimento das folhas e flores. A flor Cosmos também pode crescer a partir de sementes. Se deseja crescê-la ao ar livre, aguarde passar o período mais frio ou a estação de geada.\r\n', 'A flor Cosmos se adapta a vários tipos de umidade, porém a condição ideal de seu solo deve ser bem drenada. Por isso, assim que a Cosmos já estiver devidamente plantada, não será necessário regar as plantas, a menos que haja um período de seca intensa prolongada. Em locais onde a água é limitada, a flor Cosmos são as últimas plantas que precisam de irrigação', 'Não necessita.', 'A flor cosmos floresce o ano todo.', 'imagens_banco_de_dados/cosmos.jpg', 1, 4),
(14, 'Orquídea branca', 'Orquídeas brancas são um bom exemplo de como as flores podem ser exóticas, refinadas e bem simples, tudo isso simultaneamente. Com sua beleza, é praticamente impensável não notar uma flor desta espécie, sendo comumente usadas para acrescentar o espaço com requinte, graça e elegância.\r\n\r\n', 'Todo ano. ', 'Muitas das orquídeas de presentes são envasadas erradas para um crescimento de longo prazo, geralmente estão em recipientes de plástico e cheios de musgo em volta das raízes. Contudo, mesmo que o recipiente atual da sua planta não seja o ideal, não tente fazer o replantio de uma planta em floração senão ela vai se estressar e perder suas flores.\r\n\r\nApós a floração, corte a haste com as flores mortas e replante em um vaso específico para uma orquídea com o substrato certo. Os vasos para orquídeas possuem buracos de drenagem para que a água escorra pelo meio do vaso.\r\nPropagar uma orquídea através de sementes é bem complicado, já que as sementes minúsculas precisam de condições muito especificas que são difíceis de reproduzir. Por isso, a forma mais usada para propagar essa planta é a divisão.\r\nSe você quer propagar uma orquídea por divisão é preciso umedecer sua planta para remover de seu recipiente, depois retire as partes danificadas ou mortas, em seguida separe algumas das raízes e caules e por fim replante as plantas em um novo vaso, use estacas se for preciso e regue um pouco.\r\n\r\nDepois coloque terra, também pode usar esterco ou húmus, adicione um pouco de areia e misture bem. Pegue um galho de uma onze-horas adulta, retire as folhas e enterre este galho de 2 a 3 centímetros de profundidade, após é só umedecer o solo do recipiente.\r\n\r\n', 'Essa espécie de planta não necessita de muita água, suas raízes são feitas para absorver água rapidamente. Orquídeas brancas precisam de períodos regulares de secagem alternados com uma rega abundante.', 'Para sua orquídea é indispensável a adubação regular, porém, o adubo deve ser suave e se possível use um adubo diluído. Então, você precisa enriquecer o solo da planta com adubos do tipo NPK 20-20-20 ou o NPK 10-10-10 a cada duas semanas, lembre-se de usar só metade da quantidade indicada.', 'A floração ocorre na primavera e no outono, contudo, podem florescer mais vezes durante o ano quando são bem cuidadas.', 'imagens_banco_de_dados/orquidea_branca.jpeg', 1, 4),
(15, 'Orquídea Vanda', 'Essa espécie chama a atenção não somente pelas suas belas flores, que contam com uma variedade muito grande de cores, mas também por possuir raízes muito peculiares que facilitam o seu cultivo. Isso faz com que essa seja uma das espécies mais procuradas para o cultivo pelos admiradores destas flores. ', 'Todo ano. ', 'Muitas das orquídeas de presentes são envasadas erradas para um crescimento de longo prazo, geralmente estão em recipientes de plástico e cheios de musgo em volta das raízes. Contudo, mesmo que o recipiente atual da sua planta não seja o ideal, não tente fazer o replantio de uma planta em floração senão ela vai se estressar e perder suas flores.\r\n\r\nApós a floração, corte a haste com as flores mortas e replante em um vaso específico para uma orquídea com o substrato certo. Os vasos para orquídeas possuem buracos de drenagem para que a água escorra pelo meio do vaso.\r\nPropagar uma orquídea através de sementes é bem complicado, já que as sementes minúsculas precisam de condições muito especificas que são difíceis de reproduzir. Por isso, a forma mais usada para propagar essa planta é a divisão.\r\nSe você quer propagar uma orquídea por divisão é preciso umedecer sua planta para remover de seu recipiente, depois retire as partes danificadas ou mortas, em seguida separe algumas das raízes e caules e por fim replante as plantas em um novo vaso, use estacas se for preciso e regue um pouco.\r\n\r\nDepois coloque terra, também pode usar esterco ou húmus, adicione um pouco de areia e misture bem. Pegue um galho de uma onze-horas adulta, retire as folhas e enterre este galho de 2 a 3 centímetros de profundidade, após é só umedecer o solo do recipiente.\r\n', 'A rega da orquídea Vanda deve ser feita de acordo com o local que ela estiver plantada. Caso esteja em um substrato, o correto é que a planta não seja aguada todos os dias porque isso pode prejudicar o seu desenvolvimento, visto que o excesso pode provocar problemas como fungos e bactérias.\r\n\r\n', 'Para a adubação da planta, o indicado é que se utilize NPK 20-20-20, que é específico para as orquídeas e garante melhor desenvolvimento da planta. Esse produto fará com que a orquídea tenha mais força e consiga crescer de forma saudável, além de garantir uma floração muito mais bonita.', 'A floração ocorre na primavera e no outono, contudo, podem florescer mais vezes durante o ano quando são bem cuidadas.\r\n\r\n', 'imagens_banco_de_dados/orquidea_vanda.jpg', 1, 4),
(16, 'Morango', 'O morango é uma fruta vermelha, cuja origem é a Europa. Produzida pelo morangueiro, é um fruto rasteiro. Existem várias espécies de morango, sendo a fragaria a mais comum e cultivada em várias partes do mundo.', 'Todo ano. ', 'A reprodução pode ser feita por sementes. Dê um espaçamento de 30x30 cm ou plante em vasos de médio porte.', 'A cada 3 dias.', 'Aplicar adubação foliar ou na água da irrigação.', 'É feita quando os frutos estão avermelhados quase por completo. São retirados com cuidado e colocados em recipientes rasos.', 'imagens_banco_de_dados/morango.jpg', 2, 5),
(17, 'Tomate', 'O tomate é o fruto do tomateiro. Da sua família, fazem também parte as berinjelas, as pimentas e os pimentões, além de algumas espécies não comestíveis. A palavra portuguesa tomate vem do castelhano tomate, derivada do náuatle tomatl. Esta apareceu pela primeira vez na imprensa em 1595.', 'O ano todo, exceto nas regiões de inverno intenso, onde deve ser plantado de agosto a novembro.', 'Uma sementeira (pode improvisar com bandejas de ovos) para plantar as sementes, após 25 a 30 dias, onde as plantas estarão com de 6 a 8 cm as transplante para um vaso de médio porte, uma em cada vaso.', 'Na sementeira, uma por dia, e em intervalos de 3 ou 4 dias depois do transplantio. \r\n\r\n', 'Depois do transplantio e do pegamento das mudas, deve-se fazer uma aplicação de 20 g de casca de ovo triturada por planta. Três outras aplicações devem ser feitas, a intervalos de 20 dias. ', 'De 90 a 100 dias depois do transplante os frutos devem ser colhidos conforme forem amadurecendo.', 'imagens_banco_de_dados/tomate.jpg', 2, 5),
(18, 'Pimentão', 'Pimentão ou pimento refere-se a um grupo de cultivares da espécie Capsicum annuum, muito utilizado na culinária de todo o mundo. Os vários cultivares produzem frutos com diferentes cores sendo as mais conhecidas o verde, o amarelo e o vermelho.', 'Agosto a outubro nas regiões de inverno frio e o ano todo em regiões de clima quente.', 'Uma sementeira (pode improvisar com bandejas de ovos) para plantar as sementes, após 30 a 45 dias, onde as plantas estarão com de 6 a 8 cm as transplante para um vaso de médio porte, uma em cada vaso.', 'Na sementeira, diariamente; no local definitivo, a cada 3 dias. Deve-se evitar o encharcamento.', 'Depois do transplantio e do pegamento das mudas, deve-se fazer uma aplicação de 20 g de casca de ovo triturada por planta. Três outras aplicações devem ser feitas, a intervalos de 20 dias. ', 'Os pimentões podem ser colhidos verdes ou maduros, cerca de 100 a 120 dias depois da semeadura.', 'imagens_banco_de_dados/pimentao.jpg', 2, 5),
(19, 'Pimenta', 'Pimenta é o nome comum dado a várias plantas, seus frutos e condimentos deles obtidos, de sabor geralmente picante. Porém, este termo tem acepções diferentes nos vários países lusófonos. No Brasil, o termo refere-se tanto às espécies de Capsicum como as de Piper e Pimenta.', 'Agosto a outubro nas regiões de inverno intenso e todo o ano nas regiões de clima quente.', 'Uma sementeira (pode improvisar com bandejas de ovos) para plantar as sementes, após 30 a 45 dias, onde as plantas estarão com de 6 a 8 cm as transplante para um vaso de médio porte, uma em cada vaso.', 'Na sementeira, diariamente; no local definitivo, a cada 3 dias. Deve-se evitar o encharcamento.', 'Depois do transplantio e do pegamento das mudas, deve-se fazer uma aplicação de 20 g de casca de ovo triturada por planta. Três outras aplicações devem ser feitas, a intervalos de 20 dias. ', 'Colher as pimentas maduras. Elas amadurecem entre 100 e 120 dias após a semeadura.', 'imagens_banco_de_dados/pimenta.jpg', 2, 5),
(20, 'Alface', 'A alface (Lactuca sativa) é uma hortaliça folhosa bastante consumida pelos brasileiros, principalmente em saladas. Com uma variedade de cores, formas e tamanhos, a alface se destaca pelo seu sabor agradável e refrescante e por ser fácil de preparar.\r\n\r\n', 'Todo ano.', 'Uma sementeira (pode improvisar com bandejas de ovos) para plantar as sementes. Quando as mudas estiverem com 2 ou 5 folhas e aproximadamente 10 em de altura, escolhendo-se as melhores mudas faz-se o transplantio para os vasos ou canteiros. \r\n\r\n', 'Na sementeira, duas vezes por dia. Nos canteiros definitivos, diariamente. ', 'Mais ou menos 25 dias após o transplante faz-se a adubação em cobertura com 3g de sulfato de amônia ou 1g de uréia por planta.', 'Entre 40 e 60 dias depois da semeadura pode-se começar a colheita das plantas mais desenvolvidas', 'imagens_banco_de_dados/alface.jpg', 2, 6),
(21, 'Coentro', 'O coentro é uma hortaliça folhosa rica em compostos fenólicos, como carotenoides, taninos, flavonoides e saponinas que promovem benefícios para a saúde, como controle dos níveis de colesterol e glicose no sangue, evitando doenças como infarto e diabetes.', 'Setembro a março. Em regiões onde o inverno é ameno pode ser plantado o ano todo.', 'Fazer covas com distanciamento de 20 a 30 cm se em canteiros, ou utilizar vasos pequenos e pôr entre 20 a 35 sementes dentro.', 'Regar diariamente.', 'Não necessita.', 'Cortar as folhas desenvolvidas ou arrancar as plantas com 50 a 60 dias.cortar as folhas desenvolvidas ou arrancar as plantas com 50 a 60 dias.cortar as folhas desenvolvidas ou arrancar as plantas com 50 a 60 dias.', 'imagens_banco_de_dados/coentro.jpg', 2, 6),
(22, 'Cebolinha', 'A cebolinha é a folha de uma planta originária da Europa, de nome científico Allium schoenoprasum, também conhecida popularmente como cebolinha-francesa ou cebolinho, em Portugal. É uma planta que atinge no máximo 30 cm de altura, possui folhas roliças verde-escuras e flores cor-de-rosa arredondadas. \r\n\r\n', 'Todo ano. ', 'Em sementeiras, ponha entre 30 a 40 sementes por sulcos. Deve ser feito entre 30 e 40 dias após a semeadura, num espaçamento de 20 a 25 cm entre linhas. A parte enraizada após o corte das folhas também pode ser usada para o transplantio', 'Regar diariamente.', 'Não necessita.', 'Entre 80 e 100 dias, cortando as folhas rente ao solo ou arrancando a planta toda', 'imagens_banco_de_dados/cebolinha.jpg', 2, 6),
(23, 'Amora preta', 'A amora-preta é planta arbustiva de porte ereto ou rasteiro, pertencente à famÍlia Rosaceae, gênero Rubus, da qual existem mais de trezentas espécies.', 'Todo ano. ', 'No plantio, utilizam-se mudas obtidas por métodos de estaqueamento. As mudas de estacas de raiz são colocadas no solo horizontalmente, numa profundidade de 5 a 7cm, e cobertas de imediato, a fim 19 de evitar o ressecamento, ao passo que as mudas de estacas enraizadas são plantadas a uma profundidade um pouco maior que no viveiro, devendo-se comprimir bem o solo a seu redor. Convém evitar que as raizes fiquem expostas ao ar por tempo prolongado.', 'A cada 2 dias.\r\n\r\n', 'A adubação é feita aplicando-se, no primeiro ano, 50g da fórmula 10-20-10 por planta. A partir do segundo ano, aplicam-se 100g dessa fórmula por planta, logo após o inverno.', 'Os frutos brotam a partir de agosto, sua colheita deve ser feita logo após o amadurecimento deles. \r\n\r\n', 'imagens_banco_de_dados/amora_preta.jpg', 3, 7),
(24, 'Limão siciliano', 'Originário do Sul da Itália, o limão siciliano possui casca amarela e bem grossa, é alongado e concentra menos suco em comparação ao limão mais consumido no dia a dia, o taiti. Porém, o que pouca gente sabe é que o taiti é, na verdade, uma lima ácida, enquanto o siciliano, sim, é um limão verdadeiro', 'Todo ano. ', 'Para o plantio em vasos, o tamanho mínimo para o recipiente de 80 cm x 70 cm (altura) ou capacidade de 100 litros, de maneira a permitir que raízes e caule se desenvolvam com conforto. Preencha metade do vaso com areia e a outra metade de areia preta. Utiliza mudas enxertadas para fazer o plantio, dessa forma o seu limoeiro irá frutificar muito e crescer mais rápido.\r\n\r\n', 'A rega deve ser feita um dia sim e um dia não. Devido a quantidade de areia a infiltração da água irá ocorrer de forma rápida. Observe sempre se o substrato está úmido.', 'Não precisa de adubação química.\r\n\r\n', 'A colheita deve ser feita assim que apresentarem coloração bem amarelada e exalar um perfume típico (geralmente as mudas enxertadas são vendidas com limões já crescidos), caso opte por plantio em semente, o a árvore só frutificará após 2 a 2 anos e meio da sua semeadura. \r\n\r\n', 'imagens_banco_de_dados/limão_siciliano.jpg', 3, 7),
(25, 'Jabuticaba', 'A jabuticaba ou jaboticaba é o fruto da jaboticabeira ou jabuticabeira, uma árvore frutífera brasileira da família das mirtáceas, nativa da Mata Atlântica. Com a recente mudança na nomenclatura botânica, há divergências sobre a classificação da espécie: Myrciaria cauliflora, Plinia trunciflora ou Plinia.', 'Todo ano.', 'o vaso adequado para plantar uma jabuticabeira deve possuir cerca de 50 cm de diâmetro, o preencha com uma cama de argila expandida, outra de areia e em seguida preencha com terra preta. Utiliza mudas enxertadas para ter uma planta forte e para obter frutos mais rápido.', 'A rega deve ser diária.', 'A rega deve ser diária.', 'Geralmente, frutos de jabuticabeiras plantadas por semente levam anos para aparecem, então deseja-se que plante mudas enxertadas, dessa forma, seu florescimento será mais rápido', 'imagens_banco_de_dados/jabuticaba.png', 3, 7),
(26, 'Pitanga', 'A pitanga é o fruto da pitangueira, dicotiledônea da família das mirtáceas. Tem a forma de bolinhas globosas e carnosas, de cor vermelha, laranja, amarela ou preta. Na mesma árvore, o fruto poderá ter desde as cores verde, amarelo e alaranjado até a cor vermelho-intenso, de acordo com o grau de maturação', 'Todo ano. ', 'O plantio pode ser feito por enxertia ou pela semente, pode ser em vasos ou no chão. A pitangueira não exige muito, apenas um bom substrato, uma terra sempre úmida e bastante sol.', 'Como a pitangueira exige uma terra úmida, fique de olho sempre para que seu solo não fique muito ressecado. Faça a rega regularmente.', 'Utilize adubação npk 10-10-10.', 'Ela pode dar frutos duas vezes ao ano, entre março e abril e entre outubro e janeiro.', 'imagens_banco_de_dados/pitanga.jpg', 3, 7);

--
-- Índices para tabelas despejadas
--

--
-- Índices para tabela `contato`
--
ALTER TABLE `contato`
  ADD PRIMARY KEY (`id`);

--
-- Índices para tabela `culture_data`
--
ALTER TABLE `culture_data`
  ADD PRIMARY KEY (`id`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
